### ISSUE TITLE
mvn package failed

### ISSUE THREAD

**Issue by zzj1213** [fakereplace/fakereplace#12]
[ERROR] Failed to execute goal on project fakereplace-seam2: Could not resolve dependencies for project org.fakereplace:fakereplace-seam2:jar:1.0.0.Alpha3-SNAPSHOT: The following artifacts could not be resolved: org.jboss.seam:jboss-seam:jar:2.3.0, org.fakereplace:fakereplace:jar:1.0.0.Alpha3-SNAPSHOT: Failure to find org.jboss.seam:jboss-seam:jar:2.3.0 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by ui4j** [comment]
copy https://github.com/fakereplace/fakereplace/blob/master/settings.xml to your maven\conf folder

**Comment by stuartwdouglas** [comment]
I have packaged a custom settings file with the repos and updated the readme
