### ISSUE TITLE
when will it have the release version or stable version?

### ISSUE THREAD

**Issue by daydayfantasy** [fakereplace/fakereplace#35]
like the title

**Comment by stuartwdouglas** [comment]
It's fairly unlikely to happen at this point. I have mostly been focused on Quarkus with the aim of making it start so quickly that Fakereplace is unnecessary. 

The main problem with this approach is that it is basically just a hack, which is fine if you have a large team of developers to support it, but I don't have time to do anything but the most cursory updates.
