### ISSUE TITLE
netbeans configuration

### ISSUE THREAD

**Issue by frodrigues** [fakereplace/fakereplace#7]
Hi,

I  have installed fakereplace with this enviroment:
wicket
glassfish
netbeans

In GF  jvm option put:
     <jvm-options>-javaagent:XXXXXXXXX/fakereplace.jar=xx.xx.xxx,log=trace</jvm-options>

when i run the application:

in GF:
Fakereplace listening on port 6555
Listening for transport dt_socket at address: 9009
Launching GlassFish on Felix platform
[org.fakereplace.core.DefaultEnvironment] TRACE Recording timestamp for XXXXXX
[org.fakereplace.core.DefaultEnvironment] TRACE Recording timestamp for $Proxy0
.....

lin Application log when i run mvn package:

[compiler:compile]
Compiling 1 source file to XXXXXXXXXXXXXX\target\classes

....

[fakereplace:fakereplace]
No updated classes found to replace

fakereplace dont show classes updated what  is missing ?

Best Regards,

**Comment by stuartwdouglas** [comment]
I have updated the readme with much more detailed instructions. Fakereplace can now enhance the standard IDE hot swap, so no special configuration should be required.
