### ISSUE TITLE
NoSuchMethodException when updating a new added method

### ISSUE THREAD

**Issue by gbenmansour** [fakereplace/fakereplace#9]
Hi,
We use Jboss-7.1-Final, the first time I start jboss, and I run fakereplace client everything is fine and it replaces all the classes of my project, theses classes contains one class where I added the method "getSomething()" just to test the behavior. When I make a change on this method and run the command:
mvn package fakereplace:fakereplace
the client tell me that it is updating one class and I have the following stacktrace on the server:
[org.fakereplace.integration.jbossas.JBossAsEnvironment] INFO Finding classes for service-p12.3.90001.jar
[stdout] (Fakereplace Thread) Fakereplace is replacing class class com.bdf.agora.restitution.ctrl.DemandeRestitutionManagerImpl
[stderr] (Fakereplace Thread) java.lang.RuntimeException: java.lang.NoSuchMethodException: com.bdf.agora.restitution.ctrl.DemandeRestitutionManagerImpl.getSomething()
[stderr] (Fakereplace Thread)        at org.fakereplace.replacement.MethodReplacer.handleMethodReplacement(MethodReplacer.java:177)
[stderr] (Fakereplace Thread)        at org.fakereplace.replacement.ClassRedefiner.modifyReloadedClass(ClassRedefiner.java:84)
[stderr] (Fakereplace Thread)        at org.fakereplace.replacement.ClassRedefiner.rewriteLoadedClasses(ClassRedefiner.java:51)
[stderr] (Fakereplace Thread)        at org.fakereplace.core.Agent.redefine(Agent.java:132)
[stderr] (Fakereplace Thread)        at org.fakereplace.server.FakereplaceProtocol.run(FakereplaceProtocol.java:155)
[stderr] (Fakereplace Thread)        at org.fakereplace.server.FakereplaceServer.run(FakereplaceServer.java:47)
[stderr] (Fakereplace Thread)        at java.lang.Thread.run(Thread.java:662)
[stderr] (Fakereplace Thread) Caused by: java.lang.NoSuchMethodException: com.bdf.agora.restitution.ctrl.DemandeRestitutionManagerImpl.getSomething()
[stderr] (Fakereplace Thread)        at java.lang.Class.getDeclaredMethod(Class.java:1937)
[stderr] (Fakereplace Thread)        at org.fakereplace.data.MethodData.getMethod(MethodData.java:142)
[stderr] (Fakereplace Thread)        at org.fakereplace.replacement.MethodReplacer.handleMethodReplacement(MethodReplacer.java:170)
[stderr] (Fakereplace Thread)        ... 6 more

With some debugging I think that the method "getSomething" really does not exist when using getDeclaredMethod() , but it exist inside the method ______REDEFINED_METHOD_DELEGATOR_$ like explained in "how fakereplace works" (I'm not sure here). 
How can we manage to update a methode added in a first step ?

Regards,

**Comment by stuartwdouglas** [comment]
This should have been fixed in recent updates
